spring.application.name=sistema-pedidos
server.port=8080

# Configuracion de la base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:sistemaPedidosDb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Hibernate crea las tablas al iniciar y las elimina al cerrar
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# Configuracion del pool de conexiones HikariCP
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

spring.cloud.aws.region.static=us-east-1
aws.s3.bucket=mslpbucket

app.efs.path=/app/efs

spring.rabbitmq.host=3.92.151.242
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123